### ISSUE TITLE
Interesting! Got any examples?

### ISSUE THREAD

**Issue by trusktr** [adamhaile/surplus#1]
Something like a basic todo list example or something would be awesome.

**Comment by adamhaile** [comment]
Thanks for taking a look!

Yeah, docs and examples are almost non-existent right now.  There's a minimalist todo list app at the bottom of the [S.js page](https://github.com/adamhaile/S).  

I have several test apps I've written to develop and test the API, including the standard TodoMVC.  I'll try and get that posted soon, as well as better docs.

**Comment by trusktr** [comment]
Awesome! I'd be curious to see how you'd write that [small Todo example](https://github.com/adamhaile/S/blob/master/README.md#an-example-todomvc-in-s-plus-friends) with surplus.

**Comment by ismail-codar** [comment]
@trusktr I am working a todomvc example on webpack and typescript environment for learning surplus and s.js.  I will share it when I'm done.

**Comment by adamhaile** [comment]
@ismail-codar I just started brushing up my own TodoMVC app.  If you get stuck with the limited docs available right now, let me know and I'll try to unstick you.

Since you mentioned webpack, I wrote a loader for it, available on npm as surplus-loader.  Here's an example webpack.config.js that uses it and typescript:

```javascript
'use strict';

module.exports = {
	entry: './src/main.ts',
	output: {
		filename: './dist/main.js'
	},
	resolve: {
		extensions: ['.ts', '.tsx', '.js']
	},
	module: {
		rules: [
			{ test: /\.tsx?$/, loader: 'surplus-loader!ts-loader' },
		]
	}
};
```

**Comment by ismail-codar** [comment]
Hi @adamhaile  We do the same thing at the same time :) There are 3 or 4 issue with surplus-preprocessor. But currently can be roamed around. I will post pull requests or open issues later time.

I can work  surplus-loader with webpack 2. My settings like this:
```javascript
rules: [
	{ test: /\.tsx?$/, use: ['awesome-typescript-loader', 'surplus-loader'] }
]

**Comment by adamhaile** [comment]
@trusktr I patched up my old TodoMVC implementation and [posted it up here](https://adamhaile.github.io/surplus-todomvc).  Let me know if you have any questions.
