### ISSUE TITLE
A small regular expression problem

### ISSUE THREAD

**Issue by ismail-codar** [adamhaile/surplus#10]
Hi @adamhaile  https://github.com/adamhaile/surplus/blob/master/src/preprocessor/compile.ts#L167 is problematic. As a possibility https://github.com/adamhaile/surplus/blob/master/src/preprocessor/compile.ts#L312

Currently textField is considered to svg tag.

Because `/text/.test("textField")` returns true. Usage should be as follows.
````js
function exactTest (rx, str) {
	var ex = rx.exec(str)
	return ex != null && ex[0] === str
}

exactTest(SvgOnlyTagRx, tag)

**Comment by ismail-codar** [comment]
Is the regexp usage unnecessary here. We want to exact match  and can be as `var svg = svg || SvgOnlyTags.indexOf(tag)!= -1`

**Comment by adamhaile** [comment]
It's a single char typo. In SvgOnlyTagRx, the $ anchoring the end of the match is inside the parens when it should be outside. So it only anchors the last tag, not all of them. I'm away camping with the family but will fix it as soon as I'm back.

**Comment by ismail-codar** [comment]
No hurry! sometimes need to raise head from the computer. I can go on with these kind of things I've done in my own repository. The following code can provide convenience for simulating the problem.
```js
var SvgOnlyTags =  [
    "text",
    "textPath"
],
SvgOnlyTagRx = new RegExp("^(" + SvgOnlyTags.join("|") + "$)")
SvgOnlyTagRx.test("textField")
true
```

**Comment by adamhaile** [comment]
Pushed fix.

The reason for the RX over an array search is both performance and expressive power.  I don't care nearly as much about performance in the preprocessor as I do in the runtime and generated code, but using an RX here is O(tag length) vs an array search which is O(tag length * # of SVG tags).  V8's regex implementation is [pretty darn fast](http://benchmarksgame.alioth.debian.org/u64q/regexredux.html).

**Comment by ismail-codar** [comment]
Good
