### ISSUE TITLE
es6 template literal interpreted as jsx by compiler

### ISSUE THREAD

**Issue by andyrj** [adamhaile/surplus#12]
First of all this is a really cool project, thanks for making it open source.  I think I may have stumbled upon a bug in the compiler.

I am trying to put together a SSR'd surplus project using undom and I use es6 template literal in the render.jsx that I am passing to the surplus-loader.  I am going to work around this by making the template literal into a function and moving it into it's own file, so it's not a show stopper but I thought you might be interested to know about this behavior none the less.   Below is the error message I got from the build.

```
ERROR in ./src/server/render.jsx
Module build failed: Error: unexepected value for JSX property at line 118 col 17: ``en>       <head>
          <m''
    at ERR (/mnt/data/Work/github/andyrj/idiom/node_modules/surplus-preprocessor/index.js:443:15)
    at property (/mnt/data/Work/github/andyrj/idiom/node_modules/surplus-preprocessor/index.js:311:20)
    at htmlElement (/mnt/data/Work/github/andyrj/idiom/node_modules/surplus-preprocessor/index.js:217:33)
    at codeTopLevel (/mnt/data/Work/github/andyrj/idiom/node_modules/surplus-preprocessor/index.js:185:31)
    at parse (/mnt/data/Work/github/andyrj/idiom/node_modules/surplus-preprocessor/index.js:177:12)
    at Object.preprocess (/mnt/data/Work/github/andyrj/idiom/node_modules/surplus-preprocessor/index.js:846:45)
    at Object.preprocess (/mnt/data/Work/github/andyrj/idiom/node_modules/surplus-loader/index.js:7:37)
 @ ./src/server/index.js 13:0-30
 @ multi ./src/server
```
And here is a snippet from the code causing the above in the compiler.

```js
    const route = router.match(path);
    const View = route.component;

    document.body.appendChild(<View params={route.params} />);

    /* eslint-disable */
    const html = `
      <!DOCTYPE html>
      <html lang=en>
       <head>
          <meta charset="utf-8" />
          <meta name="referrer" content="origin" />
          <meta http-equiv="X-UA-Compatible" content="IE=edge" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <title>${meta.title}</title>
          <link rel="shortcut icon" href="/favicon.ico" />
          <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />        
          ${styles}
          ${meta.reduce((acc, val) => acc + val)}
          <script src='${vendor}' defer></script>
          <script src='${main}' defer></script>
          <script id="state" type="application/json">${JSON.stringify(state)}</script>
        </head>
        ${serialize(document.body)}
      </html>`;
```

**Comment by adamhaile** [comment]
Yep, you're exactly right.  I have this on my todo list but haven't gotten to it yet.  The surplus parser doesn't do a full JS parse, rather it scans the code text for JSX expressions to compile.  It knows to ignore JSX-like text in comments and normal strings, but it doesn't yet know to ignore them in es6 template literals.  Long term I'll likely convert to babel, but I'm going to do the es6 template literal fix in the meantime.

I've only done the barest experiments with Surplus SSR so far, so I'd love to hear how it goes for you.  Another fellow, @flagello, was interested in this area, even explored a customized server-side dom lib, https://github.com/flagello/endom.  I don't know if he's still active on it though, as his github has gone quiet.

**Comment by andyrj** [comment]
Ok, didn't know it was a known issue.  If my experiment goes well I will probably throw it all into a yo generator for my own reuse.

**Comment by adamhaile** [comment]
Well, "known issue" in the sense that a week ago it occurred to me, crap, that'll probably break :).  I hadn't actually tested it yet, so thanks for the report.  I just added a punchlist for 0.5 (#13), and this is included.

**Comment by adamhaile** [comment]
Hi Andy -- 
I checked in support for template literals in bef27d60a8d2dbf7ba71ddc15e863a347b31fe49 .  Let me know if you have any issues with it.
-- Adam
