### ISSUE TITLE
Punchlist for 0.5

### ISSUE THREAD

**Issue by adamhaile** [adamhaile/surplus#13]
I'm working on an 0.5 release, but haven't been particularly transparent about what that entails, so this is a feature list and punchlist for what remains on the 0.5 release.

New features.
- Spread functions `{...fn}` are now split off to the `fn={...}` property.  `{... }` is now only for spread properties.  I'm not thrilled with the `fn=` syntax, but it's important to have an explicit split b/w spread objects and functions, and this is the best option I could construct while maintaining JSX syntax.  Other opinions welcome.  B/c this is a breaking change, I'm bumping the version number to 0.5.
- SVG support (thanks to @ismail-codar for kicking this off!)
- Attribute support.  JSX properties that are known to be attributes (like aria-*) are set with node.setAttribute() rather than node.property = .... (krausest/js-framework-benchmark#213)
- Updated plugins for webpack, rollup, browserify and gulp build tools.
- Smaller components via tuning the Surplus.createElement() function to allow for better minimization.
- Several fixes to property precedence.  The old code sometimes left a stale property around after it had disappeared from a spread, or would let a shadowed property take precedence if it was updated last, etc.
- Several fixes to corner cases: components with no properties, boolean properties, etc.
- Compiler now has an actual AST transform infrastructure, with some new transforms and optimizations added.
- The old '@' syntax if fully removed from the compiler, only JSX remains.

To do:
- [x] An actual README.  Half done now.
- [x] Merge surplus and surplus-preprocessor packages.  They're closely coupled and having different versions of the two would cause several errors.
- [x] Fix es6 template literals #12 
- [x] property aliases for HTML
- [x] (maybe) Surplus.content(), for faster all-children updating
- [x] deep hyphenated props, compiler + .d.ts support (.style-width)
- [x] tokenizer is stripping '@' chars, left over from old syntax
- [x] change handling of children for subcomponents to match React: don't always create an array, but rather give undefined -> child -> children[] for 0 -> 1 - > n children
- [x] the React .d.ts seems to do a better job of typing children.  How?  And how to copy?

**Comment by irisjay** [comment]
just pointing out, the svg support cannot be considered complete yet. the important `xlink:href`, `xmlns:xlink` attributes aren't supported yet. ive forked a potential patch at https://github.com/irisjay/iris-surplus/tree/namespace-support.

**Comment by adamhaile** [comment]
Great find!  Yes, xlink and xml namespaced attributes should be supported.  

I took a look at how React handles them.  When I can, I try to be consistent with React, if nothing else because it means much of the tooling (syntax highlighters, linters, typecheckers, etc) works for Surplus too.  

1. React handles namespaced attributes with camelcasing -- xlinkHref, xmlRole, etc -- instead of ':'.

2. There's no need for the `xmlns:xlink` declaration, since we're setting these from the DOM rather than HTML.  We can assume that all xlink attributes are in the standard xlink namespace and all xml's in the xml one.

I took some stuff from your branch and moved some things around.  I prefer to do as much as possible in transforms rather than genCode, because genCode is already fairly complex.  So I added a namespace property to JSXAttribute and set it in a transform, then added a simple check for it in genCode to output code for `setAttributeNS()`.

Let me know if it works for you!

**Comment by irisjay** [comment]
@adamhaile You're amazing! I can't believe how nice this is. 

Thanks for the tip, I should figure out how transforms and the codeGen in surplus actually works; I was fiddling around, and just wanted to get it working.

I don't miss it, but having the regular : syntax (and not having the style as a special property) allows me to directly import svg files as surplus templates, pretty cool! I don't mind following the React way, I guess. I just have to write a little transform to achieve this now.

I was surprised at style being a special property though, since the docs didn't mention it (it said the only two special properties were ref and fn). Is it something from the React convention?

By the way, is there any way to specify an attribute without a dash? Using a colon sort of allowed me to fake it.

**Comment by tinchoz49** [comment]
I @adamhaile, how are you?

I made a plugin parcel to compile Surplus JSX views. I think it can be helpful for the developers who are just starting with Surplus and need an easy way to test it. 

https://github.com/tinchoz49/parcel-plugin-surplus

btw, thanks for your work on this project, is awesome!

**Comment by adamhaile** [comment]
@tinchoz49 sorry I missed this when it came in.  A parcel plugin is great!  Do you think it's ready enough for me to list it from the surplus README page, with the others?
