### ISSUE TITLE
0.5 beta packages now on npm

### ISSUE THREAD

**Issue by adamhaile** [adamhaile/surplus#14]
Published under the @beta tag, so get them via `npm install surplus@beta`.

Still some punchlist items to go (#13), plus testing.  Any testing help welcome!

**Comment by adamhaile** [comment]
I updated the beta release.  New version is 0.5.0-beta3.  If you're using the beta version (@ismail-codar, @griebd?) please test it out!

**Comment by griebd** [comment]
so far, so good... :wink:

**Comment by adamhaile** [comment]
Grieb, I should have listened to you: a couple people have been led astray now by trying to follow the README with the 0.4 version.  I just added a comment to the homepage.
