### ISSUE TITLE
A problem with fns

### ISSUE THREAD

**Issue by ismail-codar** [adamhaile/surplus#16]
An example with 0.5.0-beta1: 
```jsx
  const dv = (
    <div fn={() => {}}>
      1<br />
      2<br />
    </div>
  );
  console.log(dv.outerHTML); //  output is <div>      1</div>
```
But same example without fn it outputs correctly.
```jsx
  const dv = (
    <div>
      1<br />
      2<br />
    </div>
  );
  console.log(dv.outerHTML); //  output is <div>      1<br>      2<br></div>
```

**Comment by adamhaile** [comment]
That's a weird one. Let me try and repro and see if I can figure out what's going on.

**Comment by adamhaile** [comment]
OK, found it.  The compiler has an optimization transformation that converts nodes with text content to assignments to the node.textContent property.  It was taking effect on any node with an initial text child, when it should have only been running on nodes with *only* text content.  I just pushed a fix and added a test for this case.

**Comment by ismail-codar** [comment]
Yes this is fixed thanks!
