### ISSUE TITLE
html entities aren't being transpiled (at least on 0.5.0-beta1)

### ISSUE THREAD

**Issue by griebd** [adamhaile/surplus#20]
Hi @adamhaile, me again...

I have just stumbled with a situation where I need some html entities, I need to include a `&nbsp;` to get tings on the correct place...

I know why it doesn't work: it is considered as text and all text nodes are created with `document.createTextNode(value)` which does treat everything as pure text...
I tried using unicode, `\u00A0`, but them the slash got escaped as it should be... If I insert the unicode char it simple vanishes during compilation...

Any suggestions/ideas?

Thanks,
Grieb.

**Comment by adamhaile** [comment]
Yeah, I really need to get entities working.  Most can be worked around by just putting the unicode character straight into your .jsx file, but `&nbsp;` may be an exception.  I tried cutting-and-pasting one into a .jsx, and it seemed to get stripped in the final output.

In the meantime, you can insert an `&nbsp;` via javascript by doing `{"\xa0"}` or `{"\u00A0"}`.  That will create a Text node at the point of insertion and set its contents to a non-breaking space.

**Comment by adamhaile** [comment]
Added support for translating HTML entities in c6b1a5df5ba4f5d908a7c9a0c3a7c94746de5d03

**Comment by griebd** [comment]
Are you planning a new beta on npm? If not I will change to git so I can test it!

**Comment by adamhaile** [comment]
Hi Adriano -- Yeah, I'm hoping to push beta2 soon.  Hitting a few more of the punchlist items now. -- Adam

**Comment by griebd** [comment]
It is working on 0.5.0-beta3!
Thanks!!!
