### ISSUE TITLE
text nodes with useless spaces/blanks

### ISSUE THREAD

**Issue by griebd** [adamhaile/surplus#21]
Hi @adamhaile, yes, me again... :stuck_out_tongue_winking_eye:

Anyway, now that you have support for html entities it would be nice to remove all useless spaces and blanks (like new lines) from text nodes.

An example:
```javascript
[...]
      <label className="form-checkbox">
        <input type="checkbox" fn={ data(user.enabled) } />
        <i className="form-icon" />
        Active
      </label>
[...]
```
Generates something like:
```javascript
[...]
    __div2_form2_div1_div3_label1 = createElement('label', "form-checkbox", __div2_form2_div1_div3);
    __div2_form2_div1_div3_label1_input1 = createElement('input', null, __div2_form2_div1_div3_lab);
    __div2_form2_div1_div3_label1_i2 = createElement('i', "form-icon", __div2_form2_div1_div3_label1);
    createTextNode('\
                   Active\
              ', __div2_form2_div1_div3_label1);
[...]
```
And "minifyed" gives something like:
```javascript
[...]A=r("label","form-checkbox",y),B=r("input",null,A),D=r("i","form-icon",A),s("              Active            ",A)[...]
```

Is it clear what I mean? At least the spaces at the beginning and end of the string should be remove as they serve nothing in the html and in the source they are only for readability. Ideally all sequences of multiple spaces could be reduced to a single space if not at the beginning nor end.

There is a exception though, `<pre>` tags... Or is there some other reason not to remove spaces?

If you would like I can have a go to implement this...

Thanks,
Grieb.

**Comment by adamhaile** [comment]
Hi Grieb --
I checked in some changes to whitespace handling, including trimming text nodes when appropriate and collapsing extra whitespace.  Whitespace removal turns out to be a fairly complicated issue.  What I've checked in follows React's approach.  There are a few surprises in their approach, but consistency has merit.  Let me know how it works for you.
-- Adam

**Comment by griebd** [comment]
It is working on 0.5.0-beta3!
Thanks!!!
