### ISSUE TITLE
question: fn and onchange on the same element and execution order...

### ISSUE THREAD

**Issue by griebd** [adamhaile/surplus#22]
Hi again @adamhaile!

If I have an element like:
```javascript
<input type="checkbox" fn={ data(user.enabled) } onChange={ () => user.setEnabled(vm.setEnableState) } />
```

Is there any guaranties that `fn` updates the value before `onChange` is fired?

Thanks, Grieb.

**Comment by griebd** [comment]
ok, I will wait for your answer on that, but in this specific case I'm misusing the tool... :wink:
it should be like:
```javascript
<input type="checkbox"
  checked={ user.enabled() }
  onChange={ () => {
    user.enabled(!user.enabled());
    user.setEnabled(vm.setEnableState);
}} />
```

**Comment by adamhaile** [comment]
data() does two-way binding, so usually you'd use it alone, not in concert with an onChange handler.  Or, you'd do React-style one-way binding, where you don't use data(), have an onChange handler, and also a dynamic property to set .checked:
```javascript
<input type="checkbox" checked={user.enabled()} onChange=(e => user.enabled(e.target.checked)} />
```
Using both data() and onChange, I genuinely don't know which will fire first.  data() subscribes via node.addEventListener(), and I don't know if the onchange property handler gets priority over that or not.

Is there a reason you've got both data() and onChange specified?  Tell me more and I can maybe offer better help.

By the way, it's on my list to circle back and make sure surplus-mixin-* are working OK with 0.5, but I haven't done that yet.  If you hit any issues, let me know!

**Comment by adamhaile** [comment]
Heh, we were both typing at the same time.

FWIW, in my own apps, I don't usually put server persistence logic into the view like this.  Instead, I attach it to the models.  So it doesn't matter where the change comes from, I'm sure to persist it.  So it would be something like:

```javascript
S.on(user.enabled, () => user.setEnabled(vm.userEnabledState))
```
Lots of apps I'm saving whole entities back to the server, so I'll:
1. use a utility [like this](https://github.com/adamhaile/surplus-todomvc/blob/a71fd45f8e4722e0f4c9b35c3d5c1b9da2ddc416/src/models.ts#L30) to make the data signals jsonable
2. save the JSONized user to the server when it changes:
```javascript
S.on(() => JSON.stringify(user), () => server.saveUser(JSON.stringify(user)), null, false)
```
The use of `S.on()` here makes it explicit that this is event-based programming, and the `false` final property means that it won't run when the computation is created but will wait until the first change.

**Comment by griebd** [comment]
so we close this one as user error! thanks!!!
