### ISSUE TITLE
question: computations and input typing

### ISSUE THREAD

**Issue by griebd** [adamhaile/surplus#24]
Hi there,

I just found something different from mithril.js! It's probably by design but I would like your suggestion for a workaround...

I have a input field, normal `fn={ data(Svalue) }`, and it has some computations to show a error message underneath it when it's empty.
Using Surplus, after something is entered on the input field the message only goes away after some change in focus.
Using mithiril.js the message goes away when the first character is entered.

Is there a way to make Surplus behave like mithril.js?

Thanks, Grieb

**Comment by ismail-codar** [comment]
Data mixin may not apply in some cases. I think you should create your own mixin. Optionally  It can be a proxy and can be call data mixin at appropriate times.

**Comment by adamhaile** [comment]
Hi Grieb -- `data` takes an optional event parameter that determines on what DOM event it pushes changes into the signal.  By default, it's 'change', which doesn't trigger until a blur event, as you noticed.  'keyup' should give you the mithril behavior.  The todomvc example uses it here: https://github.com/adamhaile/surplus-todomvc/blob/a71fd45f8e4722e0f4c9b35c3d5c1b9da2ddc416/src/views.tsx#L33. -- A

**Comment by griebd** [comment]
perfect, thanks!!! :+1:
