### ISSUE TITLE
JSfiddle/CodePen examples?

### ISSUE THREAD

**Issue by cjh9** [adamhaile/surplus#28]
Looks like an awesome library, would it be possible to provide some "hello-world" examples in CodePen or JSFiddle so you could experiment a little? Also a minified version on cdnjs that works directly in the browser?

**Comment by adamhaile** [comment]
I added the CodePen example to the readme.

As for a browser version, I have something coming in this regard.  It's a small bundle of S, Surplus, SArray and a couple other utilities, for building small "toy" applications without any compiler step.  It needs to be updated for 0.5 and then I'll post.

**Comment by ismail-codar** [comment]
This demo is currently not working.

**Comment by adamhaile** [comment]
Thanks Ismail!  Weird issue: somehow a newer version of rollup got into the build for surplus-mixin-data, changing the way the exports worked in UMD.  Fixed it by reinstalling all node_modules and rebuilding.
