### ISSUE TITLE
Feature request: hide false-y attributes

### ISSUE THREAD

**Issue by matthew-dean** [adamhaile/surplus#37]
I had a hidden attribute like `hidden={ hideQuotes }`. I knew in my demo app that hideQuotes would default to undefined, which I hoped (spoiled by Vue and Polymer, I know) would just remove the `hidden` attribute.

I tried `hidden={ hideQuotes }` (casting to boolean), but ended up with `hidden="false"` which, in HTML, means `hidden == true` in terms of the property. HTML specifies that boolean attributes should be absent when false, but would be nice if they were also absent when falsey.

**Comment by adamhaile** [comment]
This is working now for any JSX property that is set as a attribute of the node, not a property.  So that includes any SVG property, and any HTML property which is a known attribute, like aria-hidden.
