### ISSUE TITLE
HTML Entity is escaped in 0.4.3

### ISSUE THREAD

**Issue by LeslieJohnson** [adamhaile/surplus#44]
In the little README.md todo demo the &times; entity shows as `&times;` in a text node. This also happens in my own Surplus code. My workaround has been to substitute `&times;` with `{String.fromCharCode(255)}` etc. so it's pretty low priority.

**Comment by griebd** [comment]
is this not a duplicate of #20?

**Comment by LeslieJohnson** [comment]
Yeah, you're right. I'll close it.
