### ISSUE TITLE
Questions about content.ts

### ISSUE THREAD

**Issue by brodybits** [adamhaile/surplus#48]
When I look through both the generated code for the minimalist ToDos example in CodePen [with help from console.log(comple(...))] and surplus-todomvc (<https://github.com/adamhaile/surplus-todomvc/blob/master/dist/main.js>) I do not see where the code from `content.ts` would actually be used. Any pointers?

I also noticed an internal `reconcileArrays` function in `content.js`, unfortunately do not really understand the purpose; wondering if it may suffer from VDOM-like performance issues under certain circumstances. It would be great if you can explain this a little and maybe document how we can avoid this? Any chance we can move the array processing into another module or perhaps find a way to get rid of it?

**Comment by adamhaile** [comment]
All the Surplus.* functions are runtime utilities used by the code emitted by the compiler.  They're not intended for public use, really, and they change as the compilation strategy changes.  They're currently bundled with the compiler to try and insure version compatibility: even minor point releases may differ.

Surplus.content() is the newest of those facilities.  It's used for patching children into a node: `<div>{children}</div>`.  If `children` is an update, and both the current and past value of it were arrays, then `reconcileArrays()` compares the two arrays to determine the minimal DOM ops to make the div's content match the new children.

**Comment by brodybits** [comment]
Thanks. Would using SArray help avoid the need to do `reconcileArrays()`?

**Comment by irisjay** [comment]
No, it won't, if I'm not mistaken. No matter what you use for generating the array of children, you still need to attach that to the dom and replace the previous children. `reconcileArrays ()` really finds the minimal dom operations to achieve that in case anything was reused between the two arrays, before and after, so you won't have to detach and reattach them. The worse case in the `reconcileArrays ()` would just be the function concluding it has to scrap all the old nodes and replace them with new nodes, but once again, surplus has no vdom, the used memory, etc would not be doubled.

**Comment by brodybits** [comment]
Thanks!
