### ISSUE TITLE
Typescript transpiled code support for input statement

### ISSUE THREAD

**Issue by ismail-codar** [adamhaile/surplus#5]
### Example Typescript code.
```typescript
import { MdButton } from "md-components/button";

export = (ctrl: any) =>
    <MdButton>Button 1</MdButton>
```
#### Outputs to (in typescript 2.3.4 and jsx=preserve settings)
```js
var button_1 = require("md-components/button");
module.exports = function (ctrl) {
    return <button_1.MdButton>Button 1</button_1.MdButton>;
};
```
The above code is failing: `Error: unrecognized content in begin tag at line 3 col 17: ``.MdButton>Button 1</button_1.M''`

But using `const MdButton = require("md-components/button").MdButton` instead of `import ` is working.

**Comment by ismail-codar** [comment]
I have checked latest code. Unit tests are can be misleading sometimes. I do human tests..

#### Tested jsx file:
```js
import * as Surplus from 'surplus';
Surplus;
import { MdcButton} from "../components/button";

export = (ctrl: any) =>
    <section className="hero">
        <MdcButton>Flat</MdcButton>
    </section>
```

#### Current output:
```js
"use strict";
const Surplus = require("surplus");
Surplus;
const button_1 = require("../components/button");
module.exports = (ctrl) => (function () {
    var __, __button_1.MdcButton1, __insert1;
    __ = Surplus.createElement('section', "hero", null);
    __insert1 = Surplus.createTextNode('', __)
    Surplus.S(function (range) { return Surplus.insert(range, button_1.MdcButton({
    textContent: 'Flat',
    children: []
})); }, { start: __insert1, end: __insert1 });
    return __;
})();
```

#### Result:
* `var __button_1.MdcButton1` is wrong on line 6
* `textContent: 'Flat'` may be wrong. MdcButton is not real dom it is a custom component. `children: ['Flat']` is correct result.

**Comment by ismail-codar** [comment]
Currently I am using [dotted-identifier-remover](https://github.com/ismail-codar/surplus-material/blob/master/webpack-custom-util/dotted-identifier-remover.js) as a wepack loader for this issue. It replacing all `button_1.MdButton` to `Button_1MdButton`

**Comment by adamhaile** [comment]
This is great!  Thanks for the bug reports, Ismail.

Yep, these are both regressions from recent checkins.  I just pushed a fix for the invalid identifier, and will hit the bad children in a bit.

**Comment by adamhaile** [comment]
Pushed fix for erroneous promotion of subcomponent text children to textContent properties

**Comment by ismail-codar** [comment]
Recent submissions seem to work correctly.
