### ISSUE TITLE
Move dom.ts functions into a separate repository?

### ISSUE THREAD

**Issue by brodybits** [adamhaile/surplus#50]
It looks to me like the most important runtime functions in this project are in `dom.ts`. Looking at <https://github.com/adamhaile/surplus-todomvc/blob/master/dist/main.js> it does not seem to use functions from any of the other modules in this repository.

**Comment by brodybits** [comment]
Goes against mono repo idea in #25.

**Comment by irisjay** [comment]
See #13
 > Merge surplus and surplus-preprocessor packages. They're closely coupled and having different versions of the two would cause several errors.

**Comment by brodybits** [comment]
Understood, thanks.
