### ISSUE TITLE
boolean=false attributes being omitted

### ISSUE THREAD

**Issue by jzhang1** [adamhaile/surplus#53]
I have an <input type="text" spellCheck={false}/>
The spellCheck attribute is being omitted.

**Comment by adamhaile** [comment]
Interesting.  The DOM property is `spellcheck`, but React decided to call it `spellCheck`.  I just updated the latest beta with some special cases for this and a few others where React had different casing than the DOM.  Let me know if it works for you now!

**Comment by adamhaile** [comment]
Closing this, as there are tests that cover this case and I believe it is resolved.  Thanks for the report!
