### ISSUE TITLE
Getting a circular dependency warning with Rollup

### ISSUE THREAD

**Issue by Qix-** [adamhaile/surplus#78]
While this is a warning and doesn't seem to have any negative effect on the build process or outcome, is there a way to remove the cyclic dependency?

```
(!) Circular dependency: node_modules/surplus/es/index.js -> node_modules/surplus/es/insert.js -> node_modules/surplus/es/index.js
(!) Circular dependency: node_modules/surplus/es/index.js -> node_modules/surplus/es/content.js -> node_modules/surplus/es/index.js
(!) Circular dependency: node_modules/surplus/es/index.js -> node_modules/surplus/es/spread.js -> node_modules/surplus/es/index.js
```

**Comment by leeoniya** [comment]
see also https://github.com/rollup/rollup/issues/2271

**Comment by Qix-** [comment]
Good to know, thank you @leeoniya

**Comment by Qix-** [comment]
I'm actually not seeing them anymore - at least, not when using Gulp + Rollup.

**Comment by Qix-** [comment]
Yeah pretty sure this is a problem with rollup. Ignore ^^

**Comment by WesSouza** [comment]
If your code relies on circular dependencies, you can suppress the warnings using `onwarn`, which doesn't seem to be properly documented:

```js
// rollup.config.js
export default [
  {
    // ...
    onwarn: (warning, defaultHandler) => {
      if (warning.code === "CIRCULAR_DEPENDENCY") {
        return;
      }
      defaultHandler(warning);
    },
  },
];
```
