### ISSUE TITLE
Emoijs aren't encoded correctly

### ISSUE THREAD

**Issue by Qix-** [adamhaile/surplus#79]
It appears as though emojis (and I would imagine other higher Unicode characters) are not being encoded correctly. 

```html
<div>
    🍔
</div>
```

appears to get encoded down to:

```javascript
__.textContent = "ðŸ”";
```

**Comment by derekhawker** [comment]
Could this be related to how emjois are treated in javascript strings? [https://github.com/orling/grapheme-splitter](https://github.com/orling/grapheme-splitter). 

I haven't noticed a problem when working with Surplus, though. I tried using Firefox's dev tools to look at the source for a JS file that used your emoji snippet and it didn't notice anything odd about the encoding. It displayed without any trouble in Firefox, too.

![emoji-src](https://user-images.githubusercontent.com/1403641/49735198-8befc880-fc54-11e8-87e0-0d6398a5c5be.png)

**Comment by adamhaile** [comment]
Surplus is just using Javascript's standard Unicode strings, so there shouldn't be an issue internally, but who knows?

Your example appears to work running in a browser: [Surplus issue #79](https://codepen.io/adamhaile/pen/QzwybR?editors=1000)

What's your build setup?  Webpack with surplus-loader or something else?  I wonder if your text encoding is being messed up somewhere.

**Comment by Qix-** [comment]
Rollup in this case. I can see if it's another plugin doing the mangling, I'm not near a computer at the moment.

**Comment by Qix-** [comment]
Going to assume it's rollup again - Parcel has no problem with this.
