### ISSUE TITLE
svg xlink support?

### ISSUE THREAD

**Issue by Qix-** [adamhaile/surplus#88]
Hey Adam! Hope all's well.

I've seen svg's `xlink` attributes mentioned before but was there ever support added? If not, can this issue serve as the feature request? :)

I haven't tried, but I think I can work around it using a clever `fn={...}` for now, but first class support would be awesome as well.

**Comment by adamhaile** [comment]
As part of Surplus' React compatibility, it supports React's `xlinkFoo` style namespacing of `xlink` attributes.  There's a test case of this for `xlinkHref`:
```
    it("can have xlink namespaced attributes", function () {
        var code = window.SurplusCompiler.compile(`
            var circle = <circle xlinkHref="#foo"></circle>;
            expect(circle.getAttributeNS("http://www.w3.org/1999/xlink", "href")).toBe("#foo");
        `);

        eval(code);
    });
```
Does that get you what you were looking for?  Or did you try this and something was broken :( ?

**Comment by Qix-** [comment]
Oh TIL, I didn't know that was a thing. That should fix it :) Thanks @adamhaile!
